app/student/forms.py
# app/student/forms.py

from wtforms.ext.sqlalchemy.fields import QuerySelectField

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextField, DateField, TextAreaField, IntegerField, validators
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired
from ..models import Project, Category, Research, Projtitle, Finproj, Doproj, Comment, User  
from flask_wtf.file import FileField, FileAllowed, FileRequired
from app import images, videos, documents

class FinprojForm(FlaskForm):
    """
    Form for student to add or edit a final year project
    """
    name = StringField('Title', validators=[DataRequired()])
    details = TextAreaField('Details', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])
    category = QuerySelectField(query_factory=lambda: Category.query.all(),
                            get_label="name")
    budget = StringField('Budget')
    details = TextAreaField('Details', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])
    deadline = DateField('Deadline', format='%m/%d/%Y', validators=(validators.Optional(),))
    submit = SubmitField('Submit')
    
class InternForm(FlaskForm):
	"""
	Form for student to apply for internship
	"""
		
	submit = SubmitField('Apply')
	
class CommentForm(FlaskForm):
	"""
	Form for student to add a comment
	"""
	comment = TextAreaField('Comment', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])
	submit = SubmitField('Submit')

	
class VoteForm(FlaskForm):
	"""
	Form student to vote a project
	"""
	submit = SubmitField('vote')

app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/student/views.py
# app/student/views.py


from flask import abort, flash, redirect, render_template, url_for, request, make_response, Response, redirect, json, jsonify, session
from flask_login import current_user, login_required

from . import student
from ..student.forms import FinprojForm, InternForm, CommentForm, VoteForm
from .. import db
from ..models import Project, Category, Research, Projtitle, Finproj, Doproj, Internship, Intern, Comment, Vote


import datetime

def check_student():
    """
    Prevent non-students from accessing the page
    """
    if not current_user.is_student:
        abort(403)

# Final Year Project Views

@student.route('student/studentprojects', methods=['GET', 'POST'])
@login_required
def list_finprojs():
    """
    List all projects
    """
    check_student()

    finprojs = Finproj.query.all()

    return render_template('student/finprojs/finprojs.html',
                           finprojs=finprojs, title="Projects and Assignments")

@student.route('student/finprojs/add', methods=['GET', 'POST'])
@login_required
def add_finproj():
    """
    Add a final year project to the database
    """
    check_student()

    add_finproj = True

    form = FinprojForm()
    if form.validate_on_submit():  	
    	user = current_user.id
    	finproj = Finproj(name=form.name.data,
    	                  category = form.category.data,
    	                  user_id = user,
    	                  details = form.details.data,
    	                  budget = form.budget.data,
    	                  deadline = datetime.datetime.utcnow(),
    	                  date = datetime.datetime.utcnow()
    	                  )
    	
    	try:
    		# add final year project to the database
    		db.session.add(finproj)
    		db.session.commit()
    		flash('You have successfully added a new project/ assignement.')
    	except:
    		# in case project name already exists
    		flash('Error: project name already exists.')
    		
    	# redirect to projects page
    	return redirect(url_for('student.list_finprojs'))

    # load projects template
    return render_template('student/finprojs/finproj.html', action="Add",
                           add_finproj=add_finproj, form=form,
                           title="Add Project or Assignment")
    	

@student.route('/student/finprojs/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_finproj(id):
    """
    Edit a project
    """
    check_student()

    add_finproj = False

    finproj = Finproj.query.get_or_404(id)
    form = FinprojForm(obj=finproj)
    user = current_user.id
    if form.validate_on_submit():
    	finproj.name = form.name.data
    	finproj.details = form.details.data
    	finproj.category = form.category.data
    	finproj.budget = form.budget.data
    	finproj.deadline = form.deadline.data
    	if user == finproj.user_id:
    		db.session.add(finproj)
    		db.session.commit()
    		flash('You have successfully edited the project.')
    		
    		# redirect to the project page
    		return redirect(url_for('student.list_finprojs'))
    		
    	else:
    		flash('You can only edit the project you created.')
    		# redirect to the project page
    		return redirect(url_for('student.list_projtitles'))

   
    form.name.data = finproj.name
    form.category.data = finproj.category
    form.details.data = finproj.details
    form.budget.data = finproj.budget
    form.deadline.data = finproj.deadline
   
    return render_template('student/finprojs/finproj.html', action="Edit",
                           add_finproj=add_finproj, form=form,
                           finproj=finproj, title="Edit Project or Assignment")
                           
                           
# Internship Views

@student.route('student/internships', methods=['GET', 'POST'])
@login_required
def list_internships():
    """
    List all internships
    """
    check_student()

    internships = Internship.query.all()

    return render_template('student/intern/internships.html',
                           internships=internships, title="Internship Placements")
                           
# Interns views                          
@student.route('/student/interns', methods=['GET', 'POST'])
@login_required
def list_interns():
    """
    List all interns
    """
    check_student()

    interns = Intern.query.all()

    return render_template('student/intern/interns.html',
                           interns=interns, title="Interns")
                           
@student.route('/student/interns/add/<int:id>', methods=['GET', 'POST'])
@login_required
def apply_internship(id):
    """
    Add internship application to the database
    """
    check_student()
    interns = Intern.query.all()
    add_intern = True
    internship = Internship.query.get_or_404(id)
    form = InternForm()
    if form.validate_on_submit():  	
    	user = current_user.id
    	for inter in interns:
    		if inter.user_id == user and inter.internship_id == internship.id:
    			flash('You have already appiled for this internship placement.')
    			return redirect(url_for('student.list_internships'))
    			
    	interne = Intern(internship_id = internship.id, user_id = user, date = datetime.datetime.utcnow())
    	
    	try:
    		# add internship application to the database
    		db.session.add(interne)
    		db.session.commit()
    		flash('You have successfully applied for internship.')
    		return redirect(url_for('student.list_interns'))
    		
    	except:
    		# in case the application fails
    		flash('Error: the internship application was unsuccessful.')
    		
    		# redirect to the interns page
    		
    	

    # load interns template
    return render_template('student/intern/intern.html', action="Add",
                           apply_internship=apply_internship, form=form,
                           title="Apply for Internship")
    	
                           
# Research views                          
@student.route('/student/researchs', methods=['GET', 'POST'])
@login_required
def list_researchs():
    """
    List all research
    """
    check_student()

    researchs = Research.query.all()

    return render_template('student/researchs/researchs.html',
                           researchs=researchs, title="Available Research")

                      
# Projects views                          
@student.route('/student/getProjects', methods=['GET'])
@login_required
def getProjects():
    """
    Get all projects
    """
    check_student()

    projects = Project.query.all()
    projects_dict = []
    for project in projects:
    	project_dict = {'Id':project.id,
    					'Title':project.name,
    					'Description':project.description,
    					'Category':project.category.name,
    					'By':project.user.first_name,
    					
    					'FilePath':project.img_url}
    	projects_dict.append(project_dict)
    	
    return json.dumps(project_dict)
    
   

@student.route('/student/projects/list_projects', methods=['POST','GET'])
@login_required
def list_projects():
	"""
	list all projects
	"""
	return render_template('/student/projects/projects.html')
	
@student.route('/addUpdateLike', methods=[ 'POST', 'GET'])	
@login_required
def addUpdateLike(id):
    """
    Add, update like
    """
    check_inventor()
    
    project = Project.query.get_or_404(id)
    form = ProjectForm(obj=project)
    votes = Vote.query.all()
    user = current_user.id
    
    for vot in votes:
    	if vot.user_id == user:
    		flash('You have already voted for the project.')
    		return redirect(url_for(student.list_projects))
    vote = Vote(use_id = user, project_id = project.id)
    
    project.vote = project.vote + 1
    
    db.session.add(project)
    db.session.add(vote)
    db.session.commit()
    
    return json.dumps({'status':'OK'})

# Items views                          
@student.route('/student/items', methods=['GET', 'POST'])
@login_required
def list_items():
    """
    List all items
    """
    check_student()

    stock = Stock.query.all()

    return render_template('student/items/items.html',
                           stocks=stocks, title="Items")
                           
                           
# Project titles views                          
@student.route('/student/projecttitles', methods=['GET', 'POST'])
@login_required
def list_projtitles():
    """
    List all project titles
    """
    check_student()

    projtitles = Projtitle.query.all()

    return render_template('student/projects/projtitles.html',
                           projtitles=projtitles, title="Project Titles")

# Post a comment on project   
@student.route('/student/project/add/<int:id>', methods=['GET', 'POST'])
@login_required
def comment_project(id):
    """
    Post comment on a project
    """
    check_student()

    comments = Comment.query.all()
    project = Project.query.get_or_404(id)
    form = CommentForm()
    user = current_user.id
    if form.validate_on_submit():
    	comment = Comment(message = form.comment.data,
    						user_id = user,
    						date = datetime.datetime.utcnow(),
    						project_id = project.id)
    	try:
    		#Add comment to database
    		db.session.add(comment)
    		db.session.commit()
    		flash('Your comment has been posted')
    		
    	except:
    		#In case there is a problem
    		flash('Error: Your comment was not posted')
    		
    	#redirect to Projects page
    	return redirect(url_for('student.list_projects'))
    	
    #load post comment on project template
    return render_template('student/projects/projdisc.html', action="Add",
    						comment_project=comment_project, form=form, comments=comments,
    						title="Comment on Research Project")
    						
# Post a comment on research   
@student.route('/student/research/add/<int:id>', methods=['GET', 'POST'])
@login_required
def comment_research(id):
    """
    Post comment on a research
    """
    check_student()

    comments = Comment.query.all()

app/templates/student/researchs/rechview.html
<!-- app/templates/student/researchs/rechview.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
           
   
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
          <br/>
       	   
           {{ utils.flashed_messages() }}
           <br/>
           <h1 style="text-align:center;">{{ research.Research.name }}</h1>
           <div class="row">
	    <div class="panel panel-primary">
	      <div class="panel-heading">Details</div>
	      <div class="panel-body">{{ research.Research.details }}</div>
	    </div>
	     <div class="panel panel-primary">
	      <div class="panel-heading">Category</div>
	      <div class="panel-body">{{ recipe.Category.name }}</div>
	    </div>
	    <div class="panel panel-primary">
	      <div class="panel-heading">Research was done by</div>
	      <div class="panel-body">{{ research.User.first_name }}</div>
	    </div>
	    {% if research.Research.file_url %}
	      <img src="{{ research.Research.file_url }}" alt="{{ research.Research.file_name }}" 
	      style="width:600px;height:450px;">
	    {% endif %}

          {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/student/researchs/research.html
<!-- app/templates/student/researchs/research.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
           
   Research Paper View
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
          <br/>
       	   
          
             <br/>
           <h1 style="text-align:center;">{{ research.name }}</h1>
           <div class="row">
          
	    <div class="panel panel-primary">
	      <div class="panel-heading">Details</div>
	      <div class="panel-body">{{ research.details }}</div>
	    </div>
	     <div class="panel panel-primary">
	      <div class="panel-heading">Category</div>
	      <div class="panel-body">{{ research.category.name }}</div>
	    </div>
	    <div class="panel panel-primary">
	      <div class="panel-heading">Research was done by</div>
	      <div class="panel-body">{{ research.user.first_name }}</div>
	    </div>
	    </div>
          {{ wtf.quick_form(form) }}
           <div class="row">
            <div class="panel panel-primary">
	      <div class="panel-heading">Comments</div>
	      <div class="panel-body">
	       {% for comment in comments %}
	        {% if comment.research_id == research.id %}
	         <p> {{ comment.message }} </p>
	        {% endif %}
	       {% endfor %}
	      </div>
	    </div>
	   </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/student/researchs/researchs.html
<!-- app/templates/student/researchs/researchs.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Research Papers{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Research Papers</h1>
        {% if researchs %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Heading </th>
                  <th width="40%"> Details </th>
	          <th width="40%"> Research Category </th>
	          <th width="60%"> Research Aurthur </th>
	          <th width="40%">Viewers' Comments</th>
                  <th width="15%"> View </th>
                </tr>
              </thead>
              <tbody>
              {% for research in researchs %}
                <tr>
                  <td> {{ research.name }} </td>
                  <td> {{ research.details }} </td>
		  <td> {{ research.category.name }} </td>
		  <td> {{ research.user.first_name }} </td>
		  <td>
                    <a href="{{ url_for('student.comment_research', id=research.id) }}">
                      
                       <span class="badge">  <i class="fa fa-pencil"></i>  Comments 
		        {% if research.comments %}
		         {{ research.comments.count() }}
		        {% else %}
		         0
		        {% endif %}
		      </span>
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('student.comment_research', id=research.id) }}">
                      <i class="fa fa-eye"></i> View 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No research paper has been added. </h3>
            <hr class="intro-divider">
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}