app/inventor/forms.py
# app/inventor/forms.py

from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextField, DateField, TextAreaField, IntegerField, validators, SelectField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired
from ..models import Project, Category, Research, Projtitle, Finproj, Doproj, Comment, User 
from flask_wtf.file import FileField, FileAllowed, FileRequired
from app import videos, documents, images

class CategoryForm(FlaskForm):
    """
    Form for inventor to add a category
    """
    name = StringField('Name', validators=[DataRequired()])
    details = TextAreaField('Description', render_kw={"rows":5, "cols":8}, validators=[DataRequired()])
    submit = SubmitField('Submit')

class ProjectForm(FlaskForm):
    """
    Form for inventor to add or edit a project
    """
    name = StringField('Name', validators=[DataRequired()])
    description = TextAreaField('Description', render_kw={"rows":6, "cols":8}, validators=[DataRequired()])
    instructions = TextAreaField('Instructions', render_kw={"rows":6, "cols":8})
    architecture = TextAreaField('Architecture', render_kw={"rows":6, "cols":8})
    components = TextAreaField('Components', render_kw={"rows":6, "cols":8})
    assembly = TextAreaField('Assembly', render_kw={"rows":6, "cols":8})
    concept = TextAreaField('Concept', render_kw={"rows":6, "cols":8})
    category = QuerySelectField(query_factory=lambda: Category.query.all(),
                            get_label="name")
    submit = SubmitField('Submit')
    

class ResearchForm(FlaskForm): 
    """
    Form for inventor to add or edit a research
    """
    name = StringField('Title', validators=[DataRequired()])
    details = TextAreaField('Details', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])
    category = QuerySelectField(query_factory=lambda: Category.query.all(), get_label="name")
    submit = SubmitField('Submit')
    
class CommentForm(FlaskForm):
    """
    Form for inventor to add comment
    """
    message = TextAreaField('Message', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])   
    submit = SubmitField('Submit')
    
    

class ProjtitleForm(FlaskForm):
	name = StringField('Title')
	details = TextAreaField('Details', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])
	category =  QuerySelectField(query_factory=lambda: Category.query.all(), get_label="name") 
	submit = SubmitField('Submit')  

    
class DoprojForm(FlaskForm):
    """
    Form for inventor to add or edit a doproj
    """
    name = StringField('Name', validators=[DataRequired()])
    details = TextAreaField('Details', render_kw={"rows":10, "cols":11}, validators=[DataRequired()])
    budget = StringField('Budget')
    duration = StringField('Estimated Duration') 
    submit = SubmitField('Submit')
    

app/inventor/__init__.py
from flask import Blueprint

inventor = Blueprint('inventor', __name__)

from . import views

app/inventor/views.py
# app/inventor/views.py


from flask import abort, flash, redirect, render_template, url_for, request, make_response, Response, redirect
from flask_login import current_user, login_required

from . import inventor
from ..inventor.forms import ProjectForm, CategoryForm, ResearchForm, ProjtitleForm, CommentForm
from .. import db
from ..models import Project, Category, Research, Projtitle, Finproj, Doproj, Comment
from app import videos, documents, images

import datetime

def check_inventor():
    """
    Prevent non-inventors from accessing the page
    """
    if not current_user.is_inventor:
        abort(403)

# Project Views

@inventor.route('inventor/projects', methods=['GET', 'POST'])
@login_required
def list_projects():
    """
    List all projects
    """
    check_inventor()

    projects = Project.query.all()

    return render_template('inventor/projects/projects.html',
                           projects=projects, title="Projects")
def view_project():
    """
    View the project details
    """
    check_inventor()
    
    return render_template('inventor/projects/projectview.html',
                           projects=projects, title="Project View")

@inventor.route('inventor/projects/add', methods=['GET', 'POST'])
@login_required
def add_project():
    """
    Add a project to the database
    """
    check_inventor()

    add_project = True

    form = ProjectForm()
    if form.validate_on_submit():
    	
    	user = current_user.id
    	project = Project(name=form.name.data,
    	                  category = form.category.data,
    	                  user_id = user,
    	                  instructions = form.instructions.data,
    	                  architecture = form.architecture.data,
    	                  components = form.components.data,
    	                  assembly = form.assembly.data,
    	                  concept = form.concept.data,
    	                  description=form.description.data)
    	
    	try:
    		# add project to the database
    		db.session.add(project)
    		db.session.commit()
    		flash('You have successfully added a new project.')
    	except:
    		# in case department name already exists
    		flash('Error: project name already exists.')
    		
    	# redirect to departments page
    	return redirect(url_for('inventor.list_projects'))

    # load department template
    return render_template('inventor/projects/project.html', action="Add",
                           add_project=add_project, form=form,
                           title="Add Project")
    	

@inventor.route('inventor/projects/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_project(id):
    """
    Edit a project
    """
    check_inventor()

    add_project = False

    project = Project.query.get_or_404(id)
    form = ProjectForm(obj=project)
    user = current_user.id
    if form.validate_on_submit():
       
        if user == project.user_id:
            project.name = form.name.data
            project.description = form.description.data
            project.category_id = form.category.data
            project.instructions = form.instructions.data
            project.architecture = form.architecture.data
            project.components = form.components.data
            project.concept = form.concept.data
           
            db.session.add(project)
            db.session.commit()
            flash('You have successfully edited the project.')
            
            # redirect to the projects page
            return redirect(url_for('inventor.list_projects'))
            
        else:
            flash('You can only edit the project you created.')
            # redirect to the projects page
            return redirect(url_for('inventor.list_projects'))

    form.description.data = project.description
    form.name.data = project.name
    form.category.data = project.category_id
    form.instructions.data = project.instructions
    form.architecture.data = project.architecture
    form.components.data = project.components
    form.concept.data = project.concept
   
    return render_template('inventor/projects/project.html', action="Edit",
                           add_project=add_project, form=form,
                           project=project, title="Edit Project")
                           
# Category Views

@inventor.route('inventor/categorys', methods=['GET', 'POST'])
@login_required
def list_categorys():
    """
    List all categorys
    """
    check_inventor()

    categorys = Category.query.all()

    return render_template('inventor/categorys/categorys.html',
                           categorys=categorys, title="Categorys")

@inventor.route('inventor/categorys/add', methods=['GET', 'POST'])
@login_required
def add_category():
    """
    Add a category to the database
    """
    check_inventor()

    add_category = True

    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data,       
                          details=form.details.data)
        try:
            # add category to the database
            db.session.add(category)
            db.session.commit()
            flash('You have successfully added a new category.')
        except:
            # in case category name already exists
            flash('Error: category name already exists.')

        # redirect to categorys page
        return redirect(url_for('inventor.list_categorys'))

    # load category template
    return render_template('inventor/categorys/category.html', action="Add",
                           add_category=add_category, form=form,
                           title="Add Category")
                           
# Research Views

@inventor.route('inventor/researchs', methods=['GET', 'POST'])
@login_required
def list_researchs():
    """
    List all researchs
    """
    check_inventor()

    researchs = Research.query.all()

    return render_template('inventor/researchs/researchs.html',
                           researchs=researchs, title="Research")
def view_research():
    """
    View the research details
    """
    check_inventor()
    
    return render_template('inventor/researchs/researchview.html',
                           researchs=researchs, title="Research View")

@inventor.route('inventor/researchs/add', methods=['GET', 'POST'])
@login_required
def add_research():
    """
    Add a research to the database
    """
    check_inventor() 

    add_research = True

    form = ResearchForm()
    if form.validate_on_submit():
    	fil = documents.save(request.files['doc_file'])
    	fil_url = documents.url(fil)   	
    	user = current_user.id
    	research = Research(name=form.name.data,
    						category = form.category.data,
    						user_id = user,
    						details = form.details.data,
    						file_name = fil,
    						file_url = fil_url,
    						date = datetime.datetime.utcnow())
    	
    	try:
    		# add research to the database
    		db.session.add(research)
    		db.session.commit()
    		flash('You have successfully added a new research.')
    	except:
    		# in case research name already exists
    		flash('Error: project title name already exists.')
    		
    	# redirect to researchs page
    	return redirect(url_for('inventor.list_researchs'))

    # load research template
    return render_template('inventor/researchs/research.html', action="Add",
                           add_research=add_research, form=form,
                           title="Add Research")
    	

@inventor.route('inventor/researchs/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_research(id):
    """
    Edit a research
    """
    check_inventor()

    add_research = False

    research = Research.query.get_or_404(id)
    form = ResearchForm(obj=research)
    user = current_user.id
    if form.validate_on_submit():
    	research.name = form.name.data
    	research.details = form.details.data
    	research.category = form.category.data
    	if user == research.user_id:
    		db.session.add(research)
    		db.session.commit()
    		flash('You have successfully edited your research.')
    		
    		# redirect to the researchs page
    		return redirect(url_for('inventor.list_researchs'))
    		
    	else:
    		flash('You can only edit a research you created.')
    		# redirect to the researchs page
    		return redirect(url_for('inventor.list_researchs'))

   
    form.name.data = research.name
    form.category.data = research.category
    form.details.data = research.details
    
   
    return render_template('inventor/researchs/research.html', action="Edit",
                           add_research=add_research, form=form,
                           research=research, title="Edit Research")
                           
# Project Title Views

@inventor.route('inventor/projtitles', methods=['GET', 'POST'])
@login_required
def list_projtitles():
    """
    List all project titles
    """
    check_inventor()

    projtitles = Projtitle.query.all()

    return render_template('inventor/titles/titles.html',
                           projtitles=projtitles, title="Project title")
def view_projtitle():
    """
    View the project title details
    """
    check_inventor()
    
    return render_template('inventor/titles/titleview.html',
                           projtitles=projtitles, title="Project title View")

@inventor.route('projtitles/add', methods=['GET', 'POST'])
@login_required
def add_projtitle():
    """
    Add a project title to the database
    """
    check_inventor() 

    add_projtitle = True
    user = current_user.id
    form = ProjtitleForm()
    if form.validate_on_submit():
    	projtitle = Projtitle(name=form.name.data,
    						  details = form.details.data,
    						  user_id = user,
    						  date = datetime.datetime.utcnow(),
    						  category = form.category.data)
    	
    	try:
    		# add project title to the database
    		db.session.add(projtitle)

app/templates/inventor/projects/project.html
<!-- app/templates/inventor/projects/project.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}
    {% if add_project %}
        Add Project
    {% else %}
        Edit Project
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
      <div class="center">
       {% if add_project %}
         <h1>Add Project</h1>
       {% else %}
         <h1>Edit Project</h1>
       {% endif %}
         <br/>
        {{ wtf.quick_form(form) }}
	</dv>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/inventor/projects/projects.html
<!-- app/templates/inventor/projects/projects.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Projects{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Projects</h1>
        {% if projects %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Title </th>
                  <th width="40%"> Description </th>
	          <th width="15%"> Category </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> View </th>
                </tr>
              </thead>
              <tbody>
              {% for project in projects %}
                <tr>
                  <td> {{ project.name }} </td>
                  <td> {{ project.description }} </td>
		  <td> {{ project.category.name }} </td>
                  <td>
                    <a href="{{ url_for('inventor.edit_project', id=project.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="">
                      <i class="fa fa-eye"></i> View 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No projects have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('inventor.add_project') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Project
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/inventor/projects/projectview.html
<!-- app/templates/admin/departments/department.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    View Project
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1>{{project.name}} </h1>
            <h2>Project Description </h2>
            <p>{{project.description}}</p>
            

            {% if add_department %}
                <h1>Add Department</h1>
            {% else %}
                <h1>Edit Department</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}